server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        
        # Redireciona tudo para o index.html, necessário para Aplicações Single Page (React/Vite)
        try_files $uri $uri/ /index.html;
    }
}
